module.exports = {
    'something-went-wrong': 'something-went-wrong',
    'successfull':'successfull',
    'password-mismatch': 'password and confirm password are not same.',
    'account-create-success': 'Account created successfully.',
    'account-exists': 'account already exists',
    'missing-required-fields': 'Required Fields Missing',
    'no-user-found': 'User not found.',
    'wrong-password': 'Please check your password',
    'password-updated': 'Password Successfully Updated',
    'mail-sent': 'Email Sent Successfully',
    'reactivate-account': 'Reactivate Account',
    'error-saving-user': 'Error Saving User.',
    'error-comparing-passwords': 'Error comparing passwords.',
    'error-logging-in': 'Error logging in.',
    'login-successfull': 'Succesfully logged in.',
    'error-deactivating-user': 'Error deactivating user',
    'user-deactivated': 'User Succesfully deactivated',
    'resend-email': 'Request Email Verification Again'
}
